# Generated by Django 2.2.2 on 2019-07-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
