# Generated by Django 2.2.2 on 2019-07-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0002_question_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100000)),
                ('answer', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
