# Generated by Django 2.2.2 on 2019-07-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userman', '0004_auto_20190713_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='hello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=10)),
                ('b', models.CharField(max_length=500)),
                ('c', models.CharField(max_length=50)),
            ],
        ),
    ]
